=head1 NAME 

 Authen::AliEnSASLAliEn - A SASL wrapper for Perl

=head1 SYNOPSIS

 use Authen::AliEnSASL;
 
 my $client = $sasl->client_new("host/aliendev.cern.ch");
 my ($saslstatus,$outut,$outputlen) = $client->start("GSSAPI PLAIN");
 SEND OUTPUT TO SERVER
 my ($status,$input,$inputlen) = WAIT FOR ANSWER FROM SERVER
 do {
   ($saslstatus,,$outut,$outputlen) = $client->step($input,$inputlen);
   if($outputlen != 0) {
	SEND $OUTPUT TO SERVER
   }
   ($status,$input,$inputlen) = WAIT FOR ANSWER FROM SERVER
 }while($status ne "OKAY FROM SERVER");

=

=head1 AUTHOR 

 Jan-Erik Revsbech <revsbech@fys.ku.dk>



